spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantReservation?useSSL=false
    username: root
    password: 1234
  security:
    user:
      name: user
      password: 12345
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
  sql:
    init:
      mode: always
  server:
    port: 1433

